[package]
name = "avro-tools"
version = "0.1.0"
authors = ["Daniël Heres <danielheres@gmail.com>"]
edition = "2018"


[dependencies]
avro-rs = "0.6"
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3"}